---
# NOTE: You must include units with all quantities that are not unitless. Units will be automatically converted to SI. 
# pod reference point: 
# - to bottom of frame: 82.5mm
# - from bottom of frame to bottom of he, mounted (no shims, so give or take a bit -- probably 1/10", or +~2.54mm): 62.4mm
# - from reference to bottom of HE = 82.5 + 62.4 + 2.54mm = 147.44 (reference to bottom of hover engines)
# - sensor_laser_opto: normal readings at 6mm height (?) were at about 18.3, +25mm built-in offset, so 43.3mm - 6mm = 37.3mm distance above bottom of HE (approx)
#     ref to bottom of he (147.44) - 37.3 = 110.14 (reference to bottom of laser opto sensor ** Remember to add in the built-in 25mm offset for calculations **)


sim:
    fixed_timestep: 100 usec
    pusher:
        max_velocity: 150.0 m/s
        push_end_position: 475m  # NOTE: This is where the push will stop regardless of speed -- @todo: work this into the pusher
        push_force: 8000 N
        coast_time_usec: 1000000 usec
        brake_force: -8000 N   # Doesn't really matter, just needs to be big and negative
    tube:
        length: 1500 m
        ambient_pressure: 14.7 psi  # need to convert to pascals, or use units (e.g. 14.7 psi)
        pumpdown_pressure: .125 psi

        # Reflective strips
        reflective_strip_width: 4in
        reflective_pattern_interval: 100ft
        reflective_pattern_spacing: 4in
        # Enable/disable the 500' and 1000' strip patterns
        enable_strip_patterns: True

        # Track gaps
        track_gap_width: 5mm
        track_gap_interval: 2m
        
    sensors:
        laser_opto_1:
            he_height_offset: 12.3mm  # Note: This is the height of the laser sensor above the bottom of the hover engine. 
            sampling_rate: 250 Hz
            dtype: 'f'
            noise:
                scale: 0.01
                center: 0.0
        laser_contrast_1:
            something: 1
    pod:
        mass: 350 kg
        position: 0.0 m  # from start of track
        velocity: 0.0 m/s
        acceleration: 0.0 m/s^2
        forces:
            aero:
                # Put aero drag/lift force constants and configuration here
                # @see https://rloop.slack.com/archives/eng-numsim/p1483130166001034 and https://rloop.slack.com/archives/eng-numsim/p1483130642001039
                drag_area: 1.14 m^2
                drag_coefficient: 1.1849
                air_density: 0.100098 kg/m^3
            brakes:
                # Put brake drag/lift force constants and configuration here. Include units! (any provided units will be converted to SI)
            gimbals:
                # Put gimbal drag/lift force constants and configuration here. Include units! (any provided units will be converted to SI)
            hover_engines:
                # Put hover engine drag/lift force constants and configuration here. Include units! (any provided units will be converted to SI)
                lift:
                    a: 1142
                    b: -99.144
                    c: 0.089501
                    k: 0.00932005
            landing_gear:
                # Put landing gear drag/lift force constants and configuration here. Include units! (any provided units will be converted to SI)
            lateral_stability:
                # Put lateral stability drag/lift force constants and configuration here. Include units! (any provided units will be converted to SI)
                damping_coefficient: 0.01 N*s/m  # 0.01 is a placeholder @todo: update to actual value
        landing_gear:
            # Heights relative to the bottoms of the hover engines
            min_height: 6mm
            max_height: 16mm
            initial_height: 6mm
            down_speed_loaded: something
            down_speed_unloaded: something
            up_speed_loaded: something
            down_speed_loaded: something
        sensors:
            CONTRAST_1: 
                pod_ref_x_offset: -0.5m
            CONTRAST_2:
                pod_ref_x_offset: -0.7m
            CONTRAST_3:
                pod_ref_x_offset: -0.9m                
            LASER_DIST:
                pod_ref_x_offset: 0.8m    
            ACCEL_1:
                # The accelerometer is not going to be perfectly zeroed, so let's give it a bit of an initial error that will need to be mathematically corrected
                mount_roll:
                mount_pitch: 
                mount_yaw:  
        actuators:
            lgu_actuators:  "Should be a list or something"
        physical:
            nose_tip_offset: 1.0m
            pusher_plate_offset: -2.9m
        hover_engines:
            # @see pod.py -- these are for a single hover engine drag based on velocity and height 
            mu_naught: 4 *pi 
            z_naught: 
            mag_dipole_strength:
            mag_permeability: 
            material_thickness: 0.5 in
            material_density: 
            # With this and velocity, we can get F_lift and F_drag? 
        brakes:
            BRAKE_L:
                sensors: pass
                actuators: pass
            BRAKE_R:
                sensors: pass
                actuators: pass

        
