---
# NOTE: You must include units with all quantities that are not unitless. Units will be automatically converted to SI. 
sim:
    fixed_timestep: 50000 usec
    tube:
        length: 1500 m
        ambient_pressure: 14.7 psi  # need to convert to pascals, or use units (e.g. 14.7 psi)
        pumpdown_pressure: .125 psi
        track_gap_width: 5mm
        track_gap_interval: 2m
    pusher:
        push_force: 8000 N
        max_velocity: 150.0 m/s
        coast_time_usec: 1000000 usec
        brake_force: -8000 N   # Doesn't really matter, just needs to be big and negative
    sensors:
        laser_opto_1:
            pod_height_offset: 18.3mm  # Note: this should be the x distance between the sensor and the pod reference point (once pod height is calculated)
            sampling_rate: 10000 Hz
            buffer_size: 1000   # This is not used right now
            dtype: 'f'
            noise:
                scale: 0.01
                center: 0.0         
    pod:
        mass: 350 kg
        forces:
            aero:
                # Put aero drag/lift force constants and configuration here
                # @see https://rloop.slack.com/archives/eng-numsim/p1483130166001034 and https://rloop.slack.com/archives/eng-numsim/p1483130642001039
                drag_area: 1.14 m^2
                drag_coefficient: 1.1849
                air_density: 0.100098 kg/m^3
            brakes:
                # Put brake drag/lift force constants and configuration here. Include units! (any provided units will be converted to SI)
            gimbals:
                # Put gimbal drag/lift force constants and configuration here. Include units! (any provided units will be converted to SI)
            hover_engines:
                # Put hover engine drag/lift force constants and configuration here. Include units! (any provided units will be converted to SI)
            landing_gear:
                # Put landing gear drag/lift force constants and configuration here. Include units! (any provided units will be converted to SI)
            lateral_stability:
                # Put lateral stability drag/lift force constants and configuration here. Include units! (any provided units will be converted to SI)
        sensors:
            CONTRAST_1: 
                pod_ref_x_offset: -0.5m
            CONTRAST_2:
                pod_ref_x_offset: -0.7m
            CONTRAST_3:
                pod_ref_x_offset: -0.9m                
            LASER_DIST:
                pod_ref_x_offset: 0.8m    
            ACCEL_1:
                # The accelerometer is not going to be perfectly zeroed, so let's give it a bit of an initial error that will need to be mathematically corrected
                mount_roll:
                mount_pitch: 
                mount_yaw:  
        actuators:
            lgu_actuators:  "Should be a list or something"
        physical:
            nose_tip_offset: 1.0m
            pusher_plate_offset: -2.9m
        hover_engines:
            # @see pod.py -- these are for a single hover engine drag based on velocity and height 
            mu_naught: 4 *pi 
            z_naught: 
            mag_dipole_strength:
            mag_permeability: 
            material_thickness: 0.5 in
            material_density: 
            # With this and velocity, we can get F_lift and F_drag? 
        brakes:
            BRAKE_L:
                sensors: pass
                actuators: pass
            BRAKE_R:
                sensors: pass
                actuators: pass
        landing_gear:
            LG_FL: pass
            LG_FR: pass
            LG_RL: pass
            LG_RR: pass            
        
        
